import { header } from "../sections/header.js";
import { hero } from "../sections/hero.js";
import { thisIsMe } from "../sections/thisIsMe.js";
import { aboutMe } from "../sections/aboutMe.js";
import { myOfferedServices } from "../sections/myOfferedServices.js";
import { factNumber } from "../sections/factNumber.js";
import { portfolio } from "../sections/portfolio.js";
import { feedback } from "../sections/feedback.js";
import { plans } from "../sections/plans.js";
import { blog } from "../sections/blog.js";
import { brands } from "../sections/brands.js";
import { footer } from "../sections/footer.js";

header();
hero();
thisIsMe();
aboutMe();
myOfferedServices();
factNumber();
portfolio();
feedback();
plans();
blog();
brands();
footer();